### ISSUE TITLE
Adjusting point costs in a fork for local rules?

### ISSUE THREAD

**Issue by Oilerx7** [geordanr/xwing#485]
Hi there! This is a truly spectacular piece of work. Our local group uses the squad builder for all our regular games, but often uses alternative points costing for some of the particularly powerful cards in casual games. I was hoping to try a fork where I might be able to play around with the point values of cards, but my ability to read code is pretty shabby. Is one of the files directly editable to adjust this kind of thing?
Many thanks for your time!
Peter

**Comment by geordanr** [comment]
You can find relevant card data in [coffeescripts/cards-common.coffee](https://github.com/geordanr/xwing/blob/master/coffeescripts/cards-common.coffee); just update the `points` values.

**Comment by Oilerx7** [comment]
Gotcha, thanks!
With your permission, may I upload the project with recosted points to a new github page at oilerx7.github.io/xwing, with a big disclaimer at the top explaining that this was not my work, and where the original is and that you wrote it?
With that said, I'm not confident I know how to set it uo on a new github page, do I just download the forked (and edited) project, and then reupload it to a new repository: Oilerx7/oilerx7.github.io? 
Again if I'm not going about this the right way please let me know!!!
Thanks so much for your time, if any of this isn't appropriate, please let me know, general practice when it comes to code sharing I know very little about!
Thanks!
Peter

**Comment by geordanr** [comment]
No problem: forks are exactly what GitHub is for!

For the GitHub page, what I do is build the project (with `grunt`) which creates `index.html` and all the other associated CSS and JS assets, then run `grunt gh_pages` which copies those resulting assets into `../xwing_page`.  I then commit those into a separate `gh-pages` branch of the repo, which is what the GitHub page is configured to point to (originally there wasn't a choice -- it had to be called `gh-pages` but you can choose whatever branch, now: see [the GitHub Pages docs](https://pages.github.com/) for more).

**Comment by Oilerx7** [comment]
Hey there! 
Okay, I'm still running into some trouble with this, I just kept running into errors but it turned out I wasn't installing grunt correctly. I have re-downloaded grunt as they ask on the website and installed it again. Nevertheless, I just get this error when trying to runt the command "grunt" in the bower folder. I installed grunt-cli and everything following the troubleshooting, and tried the following as well:
"npm install grunt --save-dev 
npm install grunt-serve"

but all I get is this:
">> Local Npm module "grunt-cli" not found. Is it installed?
>> Local Npm module "grunt-saucelabs" not found. Is it installed?
>> Local Npm module "grunt-contrib-connect" not found. Is it installed?
Warning: Task "default" not found. Use --force to continue.
Aborted due to warnings."

My apologies for what may be a trivial question, thanks for your time if you get the chance to help me out.

**Comment by geordanr** [comment]
You shouldn't be running grunt from the Bower folder; it's meant to be run from the repository root (where `package.json` resides).  Did you run `npm install` from the repository root?  There should be a `node_modules` folder that was created there after running `npm install`.

**Comment by Oilerx7** [comment]
Ah ok. I've probably not set up the repository root correctly. I am strongly getting the feeling I'm in over my head, as a lot of these commands are things I just don't currently understand. 

Okay, if I write out where things are and what I've done perhaps it will make sense where I've made the errors. The project title is xwing supremacy (the name of our mod).

I downloaded a clone of the repository to my computer using GitHub Desktop
This sits in
`/Users/peterholmes/Documents/GitHub/xwingsupremacy`
I tried changing this to a folder on my desktop but I just an error saying denied, so I guess it's there? Not entirely confident this is the best place for it.

so I go to that folder and enter 
`npm install`
and get
`npm WARN xwsuprem@1.0.0 No description
npm WARN xwsuprem@1.0.0 No repository field.
up to date in 0.529s`
then 
`npm install -g grunt-cli`
then
`npm init`
then 
`npm install grunt --save-dev`

but no grunt file seems to be generated at any point. 
"A valid Gruntfile could not be found. Please see the getting started guide for
more information on how to configure grunt: http://gruntjs.com/getting-started
Fatal error: Unable to find Gruntfile."

The grunt website doesn't seem to have anything on where the grunt file is generated from, or if it does I'm currently unclear on how to do it. It also says I should commit the .json file, which I frankly have no idea how to do.

Am I totally lost? or just mostly lost? :D 
Thanks!

**Comment by geordanr** [comment]
`npm install` should have installed all the necessary dependencies, including grunt.  (You still need `grunt-cli` to put `grunt` in your global path, though.)

You shouldn't need to do `npm init` as that's for initializing a new project that doesn't already have a `package.json` file.  Depending on how you answered the prompts, you may have put the project into a bad state.  Probably best to re-clone the repository from scratch and not run `npm init`.

You also don't need to run `npm install grunt` since that's already installed from `npm install` reading `package.json`.

Not being able to find a Gruntfile is strange, as `Gruntfile.coffee` [definitely exists](https://github.com/geordanr/xwing/blob/master/Gruntfile.coffee).  I suggest re-cloning the repo, just running `npm install`, and then attaching the output of `npm ls` here.  Maybe something weird is going on when installing dependencies.

**Comment by Oilerx7** [comment]
okay, I recloned the repo, ran `npm install`

and then it went a little crazy:
`npm WARN deprecated bower@1.7.9: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated bower@1.3.12: ...psst! Your project can stop working at any moment because its dependencies can change. Prevent this by migrating to Yarn: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm WARN deprecated wrench@1.4.4: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.1.14: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@0.12.1: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> node-sass@3.8.0 install /Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.8.0/darwin-x64-57_binding.node": 

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> phantomjs@1.9.20 install /Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v1.9.19/phantomjs-1.9.8-macosx.zip
Saving to /Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
  [===================================-----] 88%
Received 9187K total.
Extracting zip contents
Removing /Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/phantomjs/lib/phantom
Copying extracted folder /Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/phantomjs/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1511990005611/phantomjs-1.9.8-macosx -> /Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/phantomjs/lib/phantom/bin/phantomjs
⸨            ░░░░░░⸩ ⠋ postinstall:sass-graph: info lifecycle sass-graph@2.2.
> node-sass@3.8.0 postinstall /Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.1 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at F (/Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/which/which.js:40:28)
gyp verb `which` failed     at E (/Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/which/which.js:43:29)
gyp verb `which` failed     at /Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/which/which.js:54:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at F (/Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/which/which.js:40:28)
gyp verb `which` failed     at E (/Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/which/which.js:43:29)
gyp verb `which` failed     at /Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/which/which.js:54:16
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at F (/Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/which/which.js:40:28)\n    at E (/Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/which/which.js:43:29)\n    at /Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/which/which.js:54:16\n    at FSReqWrap.oncomplete (fs.js:152:21)' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.9.1
gyp verb command install [ '8.9.1' ]
gyp verb install input version string "8.9.1"
gyp verb install installing version: 8.9.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.9.1
gyp verb ensuring nodedir is created /var/root/.node-gyp/8.9.1
gyp verb created nodedir /var/root/.node-gyp
gyp http GET https://nodejs.org/download/release/v8.9.1/node-v8.9.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.9.1/node-v8.9.1-headers.tar.gz
gyp verb extracted file from tarball include/node/android-ifaddrs.h
gyp verb extracted file from tarball include/node/common.gypi
gyp verb extracted file from tarball include/node/config.gypi
gyp verb extracted file from tarball include/node/node.h
gyp verb extracted file from tarball include/node/node_api.h
gyp verb extracted file from tarball include/node/node_api_types.h
gyp verb extracted file from tarball include/node/node_buffer.h
gyp verb extracted file from tarball include/node/node_object_wrap.h
gyp verb extracted file from tarball include/node/node_version.h
gyp verb extracted file from tarball include/node/pthread-barrier.h
gyp verb extracted file from tarball include/node/stdint-msvc2008.h
gyp verb extracted file from tarball include/node/tree.h
gyp verb extracted file from tarball include/node/uv-aix.h
gyp verb extracted file from tarball include/node/uv-bsd.h
gyp verb extracted file from tarball include/node/uv-darwin.h
gyp verb extracted file from tarball include/node/uv-errno.h
gyp verb extracted file from tarball include/node/uv-linux.h
gyp verb extracted file from tarball include/node/uv-os390.h
gyp verb extracted file from tarball include/node/uv-posix.h
gyp verb extracted file from tarball include/node/uv-sunos.h
gyp verb extracted file from tarball include/node/uv-threadpool.h
gyp verb extracted file from tarball include/node/uv-unix.h
gyp verb extracted file from tarball include/node/uv-version.h
gyp verb extracted file from tarball include/node/uv-win.h
gyp verb extracted file from tarball include/node/uv.h
gyp verb extracted file from tarball include/node/v8-debug.h
gyp verb extracted file from tarball include/node/v8-inspector-protocol.h
gyp verb extracted file from tarball include/node/v8-inspector.h
gyp verb extracted file from tarball include/node/v8-platform.h
gyp verb extracted file from tarball include/node/v8-profiler.h
gyp verb extracted file from tarball include/node/v8-testing.h
gyp verb extracted file from tarball include/node/v8-util.h
gyp verb extracted file from tarball include/node/v8-value-serializer-version.h
gyp verb extracted file from tarball include/node/v8-version-string.h
gyp verb extracted file from tarball include/node/v8-version.h
gyp verb extracted file from tarball include/node/v8.h
gyp verb extracted file from tarball include/node/v8config.h
gyp verb extracted file from tarball include/node/zconf.h
gyp verb extracted file from tarball include/node/zlib.h
gyp verb extracted file from tarball include/node/openssl/aes.h
gyp verb extracted file from tarball include/node/openssl/asn1.h
gyp verb extracted file from tarball include/node/openssl/asn1_mac.h
gyp verb extracted file from tarball include/node/openssl/asn1t.h
gyp verb extracted file from tarball include/node/openssl/bio.h
gyp verb extracted file from tarball include/node/openssl/blowfish.h
gyp verb extracted file from tarball include/node/openssl/bn.h
gyp verb extracted file from tarball include/node/openssl/buffer.h
gyp verb extracted file from tarball include/node/openssl/camellia.h
gyp verb extracted file from tarball include/node/openssl/cast.h
gyp verb extracted file from tarball include/node/openssl/cmac.h
gyp verb extracted file from tarball include/node/openssl/cms.h
gyp verb extracted file from tarball include/node/openssl/comp.h
gyp verb extracted file from tarball include/node/openssl/conf.h
gyp verb extracted file from tarball include/node/openssl/conf_api.h
gyp verb extracted file from tarball include/node/openssl/crypto.h
gyp verb extracted file from tarball include/node/openssl/des.h
gyp verb extracted file from tarball include/node/openssl/des_old.h
gyp verb extracted file from tarball include/node/openssl/dh.h
gyp verb extracted file from tarball include/node/openssl/dsa.h
gyp verb extracted file from tarball include/node/openssl/dso.h
gyp verb extracted file from tarball include/node/openssl/dtls1.h
gyp verb extracted file from tarball include/node/openssl/e_os2.h
gyp verb extracted file from tarball include/node/openssl/ebcdic.h
gyp verb extracted file from tarball include/node/openssl/ec.h
gyp verb extracted file from tarball include/node/openssl/ecdh.h
gyp verb extracted file from tarball include/node/openssl/ecdsa.h
gyp verb extracted file from tarball include/node/openssl/engine.h
gyp verb extracted file from tarball include/node/openssl/err.h
gyp verb extracted file from tarball include/node/openssl/evp.h
gyp verb extracted file from tarball include/node/openssl/hmac.h
gyp verb extracted file from tarball include/node/openssl/idea.h
gyp verb extracted file from tarball include/node/openssl/krb5_asn.h
gyp verb extracted file from tarball include/node/openssl/kssl.h
gyp verb extracted file from tarball include/node/openssl/lhash.h
gyp verb extracted file from tarball include/node/openssl/md4.h
gyp verb extracted file from tarball include/node/openssl/md5.h
gyp verb extracted file from tarball include/node/openssl/mdc2.h
gyp verb extracted file from tarball include/node/openssl/modes.h
gyp verb extracted file from tarball include/node/openssl/obj_mac.h
gyp verb extracted file from tarball include/node/openssl/objects.h
gyp verb extracted file from tarball include/node/openssl/ocsp.h
gyp verb extracted file from tarball include/node/openssl/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/opensslv.h
gyp verb extracted file from tarball include/node/openssl/ossl_typ.h
gyp verb extracted file from tarball include/node/openssl/pem.h
gyp verb extracted file from tarball include/node/openssl/pem2.h
gyp verb extracted file from tarball include/node/openssl/pkcs12.h
gyp verb extracted file from tarball include/node/openssl/pkcs7.h
gyp verb extracted file from tarball include/node/openssl/pqueue.h
gyp verb extracted file from tarball include/node/openssl/rand.h
gyp verb extracted file from tarball include/node/openssl/rc2.h
gyp verb extracted file from tarball include/node/openssl/rc4.h
gyp verb extracted file from tarball include/node/openssl/ripemd.h
gyp verb extracted file from tarball include/node/openssl/rsa.h
gyp verb extracted file from tarball include/node/openssl/safestack.h
gyp verb content checksum node-v8.9.1-headers.tar.gz 20bba14a649ac39210a74720e399bde117ed38f95bde3548c16b36b8a1702cfc
gyp verb extracted file from tarball include/node/openssl/seed.h
gyp verb extracted file from tarball include/node/openssl/sha.h
gyp verb extracted file from tarball include/node/openssl/srp.h
gyp verb extracted file from tarball include/node/openssl/srtp.h
gyp verb extracted file from tarball include/node/openssl/ssl.h
gyp verb extracted file from tarball include/node/openssl/ssl2.h
gyp verb extracted file from tarball include/node/openssl/ssl23.h
gyp verb extracted file from tarball include/node/openssl/ssl3.h
gyp verb extracted file from tarball include/node/openssl/stack.h
gyp verb extracted file from tarball include/node/openssl/symhacks.h
gyp verb extracted file from tarball include/node/openssl/tls1.h
gyp verb extracted file from tarball include/node/openssl/ts.h
gyp verb extracted file from tarball include/node/openssl/txt_db.h
gyp verb extracted file from tarball include/node/openssl/ui.h
gyp verb extracted file from tarball include/node/openssl/ui_compat.h
gyp verb extracted file from tarball include/node/openssl/whrlpool.h
gyp verb extracted file from tarball include/node/openssl/x509.h
gyp verb extracted file from tarball include/node/openssl/x509_vfy.h
gyp verb extracted file from tarball include/node/openssl/x509v3.h
gyp verb extracted file from tarball include/node/openssl/archs/VC-WIN64A/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/VC-WIN32/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/solaris64-x86_64-gcc/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/solaris-x86-gcc/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux64-s390x/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux32-s390x/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-x86_64/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-x32/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-ppc64/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-ppc/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-elf/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-armv4/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/linux-aarch64/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/darwin64-x86_64-cc/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/darwin-i386-cc/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/BSD-x86_64/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/BSD-x86/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/aix64-gcc/opensslconf.h
gyp verb extracted file from tarball include/node/openssl/archs/aix-gcc/opensslconf.h
gyp verb extracted file from tarball include/node/libplatform/libplatform-export.h
gyp verb extracted file from tarball include/node/libplatform/libplatform.h
gyp verb extracted file from tarball include/node/libplatform/v8-tracing.h
gyp verb tarball done parsing tarball
gyp verb check download content checksum, need to download `SHASUMS256.txt`... 
gyp verb checksum url https://nodejs.org/download/release/v8.9.1/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v8.9.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.9.1/SHASUMS256.txt
gyp verb checksum data {"node-v8.9.1-aix-ppc64.tar.gz":"70c9bbb0b7e9125ba2d1e83826cd7ab981d21bf59f58b53809bb1922e59211a9","node-v8.9.1-darwin-x64.tar.gz":"05c992a6621d28d564b92bf3051a5dc0adf83839237c0d4653a8cdb8a1c73b94","node-v8.9.1-darwin-x64.tar.xz":"ed71abc42e00f9d1f55f0977ff55cad2f68f3e8693211d33922d9286e6f6540b","node-v8.9.1-headers.tar.gz":"20bba14a649ac39210a74720e399bde117ed38f95bde3548c16b36b8a1702cfc","node-v8.9.1-headers.tar.xz":"2f5e2d2bd3b5242d20a65be645b55f41e62550dfacc35d8b445f8613aec117e3","node-v8.9.1-linux-arm64.tar.gz":"47521340ff82617c1e6ba63ce300685e1b8b7cf5c0ec2e71628bcdb398085b29","node-v8.9.1-linux-arm64.tar.xz":"f774660980dcf931bf29847a5f26317823a063fa4a56f85f37c3222d77cce7c1","node-v8.9.1-linux-armv7l.tar.gz":"54efdd6a22d03294e4b6dc00338fa2d37e9740040d85638a62a3603cf31d3b26","node-v8.9.1-linux-armv7l.tar.xz":"39564e969b4098794b07e5cabf4af9efe93d1c77e0f03412bca57131bf29d671","node-v8.9.1-linux-ppc64le.tar.gz":"d3e11a9ef301afdecb10ed26470492fd03402b86bf9efc3f89a9aef541bf9a2c","node-v8.9.1-linux-ppc64le.tar.xz":"bfde0cc192859fafdcbc5f04913e4eb8cd092bb689a74f8a1fd09f9b0eeb9659","node-v8.9.1-linux-ppc64.tar.gz":"7ab8c4bf36364624b6bc7610319f1e2c32a7c882aa6392ce285faaee39597dce","node-v8.9.1-linux-ppc64.tar.xz":"e440170091d1f64d8730c59a58ea43a8fbd37bdab299e20090b319d4f6568a83","node-v8.9.1-linux-s390x.tar.gz":"48160ddaa7397cf85ca0cf333cc87dc3485956c75a3cdf98f04735bb81b37da6","node-v8.9.1-linux-s390x.tar.xz":"bf9c37cc33b524724c2e474c2745c2ba34843a8b8bf8051c8e40ab0d934965cd","node-v8.9.1-linux-x64.tar.gz":"0e49da19cdf4c89b52656e858346775af21f1953c308efbc803b665d6069c15c","node-v8.9.1-linux-x64.tar.xz":"8be82805f7c1ab3e64d4569fb9a90ded2de78dd27cadbb91bad1bf975dae1e2d","node-v8.9.1-linux-x86.tar.gz":"830f5f4ff29c2b30089a19e1b71d52d02e965b4e1f08282a09616d99aae1a42b","node-v8.9.1-linux-x86.tar.xz":"74a6e140716b2d8a240ab0760fb8edc403d06edace42659bdf8fa6de15992cf0","node-v8.9.1.pkg":"faa6397688c11458ad220c363898bd5028f1dbcf626dbe9be1c9d1d16f695e0d","node-v8.9.1-sunos-x64.tar.gz":"b40ff46aa99640235cc1d3e27abd8749425ed8ad17936dde3ebb06d0d74fed82","node-v8.9.1-sunos-x64.tar.xz":"2447d5b4cd787605d21f82159072764649910658d2f9d4f6dd2847c7380eff7c","node-v8.9.1-sunos-x86.tar.gz":"a5a31c9c211fccfa54068270ab95aab0c73d05d789d9cbc16fc521e1e4698c2c","node-v8.9.1-sunos-x86.tar.xz":"813dc3cdbfe061dd39efac2cf55679a2c03d1923c6f7e61ab8db2fc158f41cf1","node-v8.9.1.tar.gz":"32491b7fcc4696b2cdead45c47e52ad16bbed8f78885d32e873952fee0f971e1","node-v8.9.1.tar.xz":"ef160c21f60f8aca64145985e01b4044435e381dc16e8f0640ed0223e84f17e0","node-v8.9.1-win-x64.7z":"ff28dd5ff5a09a904e364742b58011af33d0a3fe148831e55b2c60f1bc251569","node-v8.9.1-win-x64.zip":"db89c6e041da359561fbe7da075bb4f9881a0f7d3e98c203e83732cfb283fa4a","node-v8.9.1-win-x86.7z":"a30b6a56d424f8a34e65fe8f197a6db17dee6fa10ed50ffdf8490ca0787d995a","node-v8.9.1-win-x86.zip":"e3c38a7802acf1b2e89ff172f460dd1476ffc119bbcc88aa8d5364acd9714aa2","node-v8.9.1-x64.msi":"5b747214518d62891e48ca58483df84bc3b0cea8b34176f22f92364e07ffdfc3","node-v8.9.1-x86.msi":"2269b89726b055a86e988adb39b35cdd23434302416d3be0d73697f51da3e339","win-x64/node.exe":"ef1a6f906a31d115f0a2c8abfdd1d34f62f0789abd539910838ee1b62bf22dce","win-x64/node.lib":"28c8b55b3cccfe2c2c64ba6178340ac997545f1e1e4652122724df0dbbf0380b","win-x64/node_pdb.7z":"d6a356265c7b020d72a52a3d1f7783237d2b951e2b74d81015c509d5359a06b9","win-x64/node_pdb.zip":"b8c4d963ab23c3b3e8a106d150e33c713734e9a84844549a632e2bddf8fc698c","win-x86/node.exe":"e8697af447c53faea624f854f44219107adca2d78c78a122c3ce9793aef97e2a","win-x86/node.lib":"a7956a209e0e8699977399bbe71319873898a5a70b9162d6eab4f0bfc09791c9","win-x86/node_pdb.7z":"6d0a2847d205f179e0e9b3debb264e3bb1eb89a5e2c01792e6533f581ea3ba75","win-x86/node_pdb.zip":"18a8506287415596f27c71d8e3efde37fbc3b7addb0e669c2452491891ef1a85"}
gyp verb download contents checksum {"node-v8.9.1-headers.tar.gz":"20bba14a649ac39210a74720e399bde117ed38f95bde3548c16b36b8a1702cfc"}
gyp verb validating download checksum for node-v8.9.1-headers.tar.gz (20bba14a649ac39210a74720e399bde117ed38f95bde3548c16b36b8a1702cfc == 20bba14a649ac39210a74720e399bde117ed38f95bde3548c16b36b8a1702cfc)
gyp verb get node dir target node version installed: 8.9.1
gyp verb build dir attempting to create "build" dir: /Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/var/root/.node-gyp/8.9.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/var/root/.node-gyp/8.9.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/var/root/.node-gyp/8.9.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.

xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 16.0.0
gyp ERR! command "/usr/local/bin/node" "/Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/peterholmes/Documents/GitHub/xwingsupremacy/node_modules/node-sass
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed
⸨            ░░░░░░⸩ ⠧ postinstall: info lifecycle node-sass@3.8.0~postinstal⸨            ░░░░░░⸩ ⠧ postinstall: info lifecycle node-sass@3.8.0~postinstal⸨            ░░░░░░⸩ ⠧ postinstall: info lifecycle node-sass@3.8.0~postinstal⸨            ░░░░░░⸩ ⠧ postinstall: info lifecycle node-sass@3.8.0~postinstal⸨            ░░░░░░⸩ ⠧ postinstall: info lifecycle node-sass@3.8.0~postinstal⸨            ░░░░░░⸩ ⠧ postinstall: info lifecycle node-sass@3.8.0~postinstal⸨            ░░░░░░⸩ ⠧ postinstall: info lifecycle node-sass@3.8.0~postinstal⸨            ░░░░░░⸩ ⠧ postinstall: info lifecycle node-sass@3.8.0~postinstal⸨            ░░░░░░⸩ ⠧ postinstall: info lifecycle node-sass@3.8.0~postinstalnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.8.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.8.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2017-11-29T21_13_30_896Z-debug.log`

**Comment by geordanr** [comment]
That's looking better.

Looks like `node-sass` is having trouble building, notably this error message:

```
xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
```

You may have to install the appropriate Xcode tools/libraries to build stuff (I'm not really familiar with this, though).
